#!/bin/bash
a=2;

while true
do

   echo "============================"
   echo "Select the below options"
   echo "1. To read one, press 1"
   echo "2. To read two, press 2"
   echo "============================"
echo "This is a new test."

case word in 
   1)
   echo "This is one"
   ;;
   2) 
   echo "This is two"
   ;;
   *)
   echo "This is done"
   ;;
esac

